### PR TITLE
v2.0.5: add build process + minor tweaks to code structure

### PR DESCRIPTION
**Pull request by nrednav**
## What's changed
- Project was rewritten to deduplicate code & improve DX (thanks to @Californ1a for these changes)
- Added & setup new dependencies
  - Vite
  - Prettier
  - ESLint
  - Husky
  - Lint-Staged
  - vite-plugin-web-extension

## Why
- There were duplicated source files in both extensions (firefox, chrome)
- The project could really use a build process to improve the DX of making changes, testing them & preparing releases
- ESLint & Prettier help standardize the code for future contributions

### CODE REVIEW

**Comment by Californ1a** [comment]
I also made an edit to address #7 but it's kind of a mess so I didn't send a PR for that: 

If you want to add it, here's the main function I used to get the unwatched videos (the selector is `ytd-thumbnail-overlay-resume-playback-renderer #progress`):
```js
const getUnwatchedVideos = () => {
  const videos = getVideos();
  const unwatched = videos.filter((video) => {
    if (!video) return false;

    const watchedVideoContainer = video.querySelector(config.watchedVideoContainer);
    if (watchedVideoContainer) {
      const watchPercentStr = watchedVideoContainer.style.width;
      const watchPercent = watchPercentStr ? parseInt(watchPercentStr, 10) : null;
      if (watchPercent === 100) return false;
    }

    return true;
  });
  if (!unwatched?.[0]) return null;
  return unwatched;
};
```

Then I had a few changes in `getTimestamps()` to handle unwatched videos differently, but mainly it used the width of the progress bar under the thumbnail to determine the watch %, and pass that % into `unformatTimestamp()` with the return giving the % of seconds remaining: `return watchPercent ? seconds * ((100 - watchPercent) / 100) : seconds;`

**Comment by nrednav** [comment]
@Californ1a that's pretty nifty! Is that specifically for the `Watch Later` page? I'm not opposed to adding something like this, however I'm not sure if it's something that all users would want. So if we did add this, it would probably have to be off by default & toggle-able.

I will leave it out of 2.0.5, but feel free to create a PR with the change later. From your tests, how stable is it?

**Comment by Californ1a** [comment]
>  Is that specifically for the Watch Later page?

It's on any playlist, just so you're able to see how much you still have remaining.

> off by default & toggle-able

Yeah, absolutely. Since there wasn't already an options page or browser action popup page, I didn't want to go start making one without knowing if you would want a bunch of toggles or not. The way I have it right now, it will find all videos without a progress bar on them (100% unwatched) as well as all videos with a non-100% width progress bar, and add all those timestamps (using the % width on those that have a progress bar to remove the estimated "watched" time).

But, if it were properly implemented, there should probably be toggles to count unwatched (no progress bar), as well as count partially-watched (any non-100% width progress bars). There's definitely cases where you might go back and jump around on a previous video in a playlist, maybe looking for a specific scene or whatever, and then the progress bar wouldn't be 100% anymore so you might not want to have it count the partially-watched ones as unwatched; you might only want the total time from the ones with no progress bar at all.

> From your tests, how stable is it?

I completely missed checking playlists with deleted/private stuff that doesn't show timestamps as you noticed in my initial fix PR, but in regular playlists it seems to get the unwatched time as the same amount every time.

**Comment by nrednav** [comment]
> It's on any playlist, just so you're able to see how much you still have remaining.

👍

> Yeah, absolutely. Since there wasn't already an options page or browser action popup page, I didn't want to go start making one without knowing if you would want a bunch of toggles or not

For sure, if this is something that gets implemented then an options page would be a nice addition.

> but in regular playlists it seems to get the unwatched time as the same amount every time.

Yea if it's reliant on the presence of a progress bar in order to work then I don't think it should break for deleted/private videos.

All said, it's completely up to you if you want to continue work on this, no pressure or requirement at all! You've already contributed some amazing upgrades so thanks once again 🙂

**Pull request merged**
